version: '3.7'

services:
  mysafeip:
    image: yvguim/mysafeip:0.12
    restart: unless-stopped
    container_name: mysafeip
    ports:
      - "80:80"
    volumes:
      - ./sql_app.db:/app/sql_app.db
      - ./env:/app/.env
networks:
  default:
    name: exponet
